'use client';

import Link from 'next/link';
import { useParams, useRouter } from 'next/navigation';
import { useEffect, useState } from 'react';
import { ArrowLeft, CheckCircle2, CircleDollarSign } from 'lucide-react';
import { getSupabaseBrowser } from '@/lib/supabase-browser';

type Appointment={id:number;patient_id:number;psychologist_id?:string|null;starts_at?:string|null;status?:string|null;service_rate_id?:number|null;patients?:{first_name?:string|null;last_name?:string|null}|null};
type Rate={id:number;name:string;amount:number;currency:string;consultation_mode?:string|null;duration_minutes?:number|null};
const money=(n:number,c='MXN')=>new Intl.NumberFormat('es-MX',{style:'currency',currency:c}).format(n||0);

export default function CompleteAppointmentPage(){
 const params=useParams<{id:string}>();const router=useRouter();const appointmentId=Number(params.id);const [appointment,setAppointment]=useState<Appointment|null>(null);const [rates,setRates]=useState<Rate[]>([]);const [rateId,setRateId]=useState('');const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [message,setMessage]=useState('');
 useEffect(()=>{async function load(){if(!Number.isSafeInteger(appointmentId)||appointmentId<=0){setMessage('Cita no válida.');setLoading(false);return;}const s=getSupabaseBrowser();const [{data:a,error:aError},{data:r,error:rError}]=await Promise.all([s.from('appointments').select('id,patient_id,psychologist_id,starts_at,status,service_rate_id,patients(first_name,last_name)').eq('id',appointmentId).maybeSingle(),s.from('service_rates').select('id,name,amount,currency,consultation_mode,duration_minutes').eq('active',true).order('name')]);if(aError||!a)setMessage(aError?.message||'Cita no encontrada.');else{const row=a as unknown as Appointment;setAppointment(row);if(row.service_rate_id)setRateId(String(row.service_rate_id));}if(!rError)setRates((r||[]) as unknown as Rate[]);setLoading(false);}void load();},[appointmentId]);
 async function complete(){if(!appointment)return;setSaving(true);setMessage('');try{const s=getSupabaseBrowser();const {data:{session}}=await s.auth.getSession();if(!session?.access_token)throw new Error('Sesión no válida.');const response=await fetch(`/api/appointments/${appointment.id}/complete`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({serviceRateId:rateId?Number(rateId):null})});const payload=await response.json();if(!response.ok)throw new Error(payload.error||'No se pudo completar la cita.');setMessage(payload.charged?'Cita completada y cargo generado.':'Cita completada sin generar cargo.');setTimeout(()=>router.push('/appointments'),700);}catch(err){setMessage(err instanceof Error?err.message:'No se pudo completar la cita.');}finally{setSaving(false);}}
 if(loading)return <div className="card empty-state">Cargando cita...</div>;
 if(!appointment)return <div className="card empty-state"><h2>No fue posible abrir la cita</h2><p className="error">{message}</p><Link className="btn btn-secondary" href="/appointments">Volver</Link></div>;
 const patient=appointment.patients?`${appointment.patients.first_name||''} ${appointment.patients.last_name||''}`.trim()||'Paciente':'Paciente';const selected=rates.find(x=>String(x.id)===rateId);
 return <div className="page-shell"><div className="record-breadcrumb"><Link href="/appointments"><ArrowLeft size={15}/> Agenda</Link><span>/</span><strong>Completar cita</strong></div><section className="patient-record-hero"><div className="patient-record-avatar"><CheckCircle2 size={28}/></div><div className="patient-record-copy"><span className="eyebrow">Cierre de consulta</span><h1>Completar cita de {patient}</h1><p className="muted">Marca la atención como completada y, si corresponde, genera el cargo automáticamente.</p></div></section>{message?<div className="clinical-alert" style={{margin:'18px 0'}}><span>{message}</span></div>:null}<div className="record-grid"><section className="card record-main-card"><div className="section-heading"><div><span className="eyebrow">Resumen</span><h2>Datos de la cita</h2></div></div><div className="details-list"><div><span>Paciente</span><strong>{patient}</strong></div><div><span>Fecha</span><strong>{appointment.starts_at?new Intl.DateTimeFormat('es-MX',{dateStyle:'long',timeStyle:'short'}).format(new Date(appointment.starts_at)):'—'}</strong></div><div><span>Estado actual</span><strong>{appointment.status||'Programada'}</strong></div></div></section><aside className="card record-side-card"><span className="eyebrow">Cobro</span><h2>Tarifa</h2><label className="field">Servicio<select value={rateId} onChange={e=>setRateId(e.target.value)}><option value="">Completar sin generar cargo</option>{rates.map(rate=><option key={rate.id} value={rate.id}>{rate.name} · {money(Number(rate.amount),rate.currency)}</option>)}</select></label>{selected?<div className="notice-card" style={{marginTop:14}}><CircleDollarSign size={18}/><span>Se generará un cargo por <strong>{money(Number(selected.amount),selected.currency)}</strong>.</span></div>:null}<button className="btn btn-primary" style={{marginTop:16,width:'100%'}} disabled={saving||['Completada','Cancelada','Cancelado','No asistió'].includes(appointment.status||'')} onClick={()=>void complete()}><CheckCircle2 size={16}/> {saving?'Completando...':'Completar cita'}</button></aside></div></div>;
}
