'use client';

import { FormEvent, useEffect, useMemo, useState } from 'react';
import { BadgeDollarSign, Banknote, CircleDollarSign, RefreshCw, WalletCards } from 'lucide-react';
import { getSupabaseBrowser } from '@/lib/supabase-browser';

type Patient={id:number;first_name?:string|null;last_name?:string|null};
type Charge={id:number;patient_id:number;appointment_id?:number|null;concept:string;amount:number;discount:number;currency:string;status:string;due_on?:string|null;created_at:string;patients?:Patient|null;payments?:{amount:number}[]|null};
type Appointment={id:number;patient_id:number;starts_at:string;patients?:Patient|null};
const money=(n:number,c='MXN')=>new Intl.NumberFormat('es-MX',{style:'currency',currency:c}).format(n||0);
const patientName=(p?:Patient|null)=>p?`${p.first_name||''} ${p.last_name||''}`.trim()||'Paciente':'Paciente';

export default function FinancePage(){
 const [charges,setCharges]=useState<Charge[]>([]);const [patients,setPatients]=useState<Patient[]>([]);const [appointments,setAppointments]=useState<Appointment[]>([]);const [msg,setMsg]=useState('');const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);
 const [charge,setCharge]=useState({patientId:'',appointmentId:'',concept:'Consulta psicológica',amount:'',discount:'0',dueOn:''});
 const [payment,setPayment]=useState({chargeId:'',amount:'',method:'Transferencia',reference:''});
 async function load(){setLoading(true);setMsg('');const s=getSupabaseBrowser();const [c,p,a]=await Promise.all([s.from('billing_items').select('id,patient_id,appointment_id,concept,amount,discount,currency,status,due_on,created_at,patients(first_name,last_name),payments(amount)').order('created_at',{ascending:false}).limit(200),s.from('patients').select('id,first_name,last_name').order('first_name'),s.from('appointments').select('id,patient_id,starts_at,patients(first_name,last_name)').order('starts_at',{ascending:false}).limit(100)]);if(c.error)setMsg(c.error.message);else setCharges((c.data||[]) as unknown as Charge[]);if(!p.error)setPatients((p.data||[]) as unknown as Patient[]);if(!a.error)setAppointments((a.data||[]) as unknown as Appointment[]);setLoading(false);}
 useEffect(()=>{void load();},[]);
 const calc=(x:Charge)=>{const total=Math.max(0,Number(x.amount)-Number(x.discount||0));const paid=(x.payments||[]).reduce((sum,p)=>sum+Number(p.amount||0),0);return{total,paid,balance:Math.max(0,total-paid)}};
 const metrics=useMemo(()=>charges.reduce((m,x)=>{const v=calc(x);m.billed+=v.total;m.paid+=v.paid;m.receivable+=v.balance;return m},{billed:0,paid:0,receivable:0}),[charges]);
 async function createCharge(e:FormEvent){e.preventDefault();setSaving(true);setMsg('');try{const amount=Number(charge.amount),discount=Number(charge.discount||0);if(!charge.patientId||!Number.isFinite(amount)||amount<=0||discount<0||discount>amount)throw new Error('Revisa paciente, importe y descuento.');const s=getSupabaseBrowser();const {data:{user}}=await s.auth.getUser();const result=await s.from('billing_items').insert({patient_id:Number(charge.patientId),appointment_id:charge.appointmentId?Number(charge.appointmentId):null,psychologist_id:user?.id||null,concept:charge.concept.trim()||'Consulta psicológica',amount,discount,currency:'MXN',status:'pending',due_on:charge.dueOn||null});if(result.error)throw result.error;setCharge({patientId:'',appointmentId:'',concept:'Consulta psicológica',amount:'',discount:'0',dueOn:''});await load();setMsg('Cargo registrado.');}catch(err){setMsg(err instanceof Error?err.message:'No se pudo registrar el cargo.');}finally{setSaving(false);}}
 async function registerPayment(e:FormEvent){e.preventDefault();setSaving(true);setMsg('');try{const item=charges.find(x=>String(x.id)===payment.chargeId);const amount=Number(payment.amount);if(!item||!Number.isFinite(amount)||amount<=0)throw new Error('Selecciona un cargo e importe válido.');const values=calc(item);if(amount>values.balance+0.001)throw new Error('El pago no puede superar el saldo pendiente.');const s=getSupabaseBrowser();const {data:{user}}=await s.auth.getUser();const inserted=await s.from('payments').insert({billing_item_id:item.id,amount,payment_method:payment.method,reference:payment.reference.trim()||null,received_by:user?.id||null});if(inserted.error)throw inserted.error;const remaining=Math.max(0,values.balance-amount);const status=remaining<=0.001?'paid':'partial';const updated=await s.from('billing_items').update({status}).eq('id',item.id);if(updated.error)throw updated.error;setPayment({chargeId:'',amount:'',method:'Transferencia',reference:''});await load();setMsg('Pago registrado.');}catch(err){setMsg(err instanceof Error?err.message:'No se pudo registrar el pago.');}finally{setSaving(false);}}
 return <div className="page-shell"><div className="page-head"><div><span className="eyebrow">Administración</span><h1>Finanzas</h1><p className="muted">Cargos, pagos y cuentas por cobrar de la práctica.</p></div><button className="btn btn-secondary" onClick={()=>void load()}><RefreshCw size={16}/> Actualizar</button></div>
 <section className="dashboard-stats"><article className="metric-card"><span className="metric-icon"><BadgeDollarSign size={21}/></span><span><small>Facturado</small><strong>{money(metrics.billed)}</strong></span></article><article className="metric-card"><span className="metric-icon"><Banknote size={21}/></span><span><small>Cobrado</small><strong>{money(metrics.paid)}</strong></span></article><article className="metric-card"><span className="metric-icon"><WalletCards size={21}/></span><span><small>Por cobrar</small><strong>{money(metrics.receivable)}</strong></span></article></section>
 {msg?<div className="clinical-alert" style={{margin:'18px 0'}}><span>{msg}</span></div>:null}
 <div className="record-grid" style={{marginTop:22}}><section className="card record-main-card"><div className="section-heading"><div><span className="eyebrow">Cuentas</span><h2>Movimientos</h2></div></div>{loading?<div className="empty-state compact-empty">Cargando...</div>:charges.length?<div className="appointment-list">{charges.map(x=>{const v=calc(x);return <div className="appointment-item" key={x.id}><CircleDollarSign size={18}/><div><strong>{patientName(x.patients)} · {x.concept}</strong><small>{money(v.total,x.currency)} · pagado {money(v.paid,x.currency)} · saldo {money(v.balance,x.currency)}</small></div><span className="soft-chip">{x.status}</span></div>})}</div>:<div className="empty-state compact-empty">Aún no hay cargos.</div>}</section>
 <aside style={{display:'grid',gap:18}}><section className="card record-side-card"><span className="eyebrow">Nuevo</span><h2>Registrar cargo</h2><form className="form" onSubmit={createCharge}><label className="field">Paciente<select required value={charge.patientId} onChange={e=>setCharge({...charge,patientId:e.target.value,appointmentId:''})}><option value="">Selecciona</option>{patients.map(p=><option key={p.id} value={p.id}>{patientName(p)}</option>)}</select></label><label className="field">Cita relacionada<select value={charge.appointmentId} onChange={e=>setCharge({...charge,appointmentId:e.target.value})}><option value="">Sin cita</option>{appointments.filter(a=>!charge.patientId||String(a.patient_id)===charge.patientId).map(a=><option key={a.id} value={a.id}>{new Intl.DateTimeFormat('es-MX',{dateStyle:'medium',timeStyle:'short'}).format(new Date(a.starts_at))}</option>)}</select></label><label className="field">Concepto<input value={charge.concept} onChange={e=>setCharge({...charge,concept:e.target.value})}/></label><label className="field">Importe<input type="number" min="0" step="0.01" required value={charge.amount} onChange={e=>setCharge({...charge,amount:e.target.value})}/></label><label className="field">Descuento<input type="number" min="0" step="0.01" value={charge.discount} onChange={e=>setCharge({...charge,discount:e.target.value})}/></label><label className="field">Vencimiento<input type="date" value={charge.dueOn} onChange={e=>setCharge({...charge,dueOn:e.target.value})}/></label><button className="btn btn-primary" disabled={saving}>Registrar cargo</button></form></section>
 <section className="card record-side-card"><span className="eyebrow">Cobranza</span><h2>Registrar pago</h2><form className="form" onSubmit={registerPayment}><label className="field">Cargo<select required value={payment.chargeId} onChange={e=>{const item=charges.find(x=>String(x.id)===e.target.value);setPayment({...payment,chargeId:e.target.value,amount:item?String(calc(item).balance):''})}}><option value="">Selecciona</option>{charges.filter(x=>calc(x).balance>0&&x.status!=='cancelled').map(x=><option key={x.id} value={x.id}>{patientName(x.patients)} · {x.concept} · {money(calc(x).balance)}</option>)}</select></label><label className="field">Importe<input type="number" min="0" step="0.01" required value={payment.amount} onChange={e=>setPayment({...payment,amount:e.target.value})}/></label><label className="field">Método<select value={payment.method} onChange={e=>setPayment({...payment,method:e.target.value})}><option>Transferencia</option><option>Efectivo</option><option>Tarjeta</option><option>Otro</option></select></label><label className="field">Referencia<input value={payment.reference} onChange={e=>setPayment({...payment,reference:e.target.value})}/></label><button className="btn btn-primary" disabled={saving}>Registrar pago</button></form></section></aside></div></div>;
}
