'use client';

import { FormEvent, useEffect, useState } from 'react';
import { ClipboardCheck, Save } from 'lucide-react';
import { getSupabaseBrowser } from '@/lib/supabase-browser';

type Plan = { id?: number; title: string; clinical_formulation: string; general_objective: string; approach: string; frequency: string; status: 'draft'|'active'|'completed'|'cancelled'; starts_on: string; target_end_on: string };
const emptyPlan = (): Plan => ({ title: 'Plan terapéutico', clinical_formulation: '', general_objective: '', approach: '', frequency: '', status: 'active', starts_on: new Date().toISOString().slice(0,10), target_end_on: '' });

export function TreatmentPlanPanel({ patientId, psychologistId, onSaved }: { patientId: number; psychologistId?: string | null; onSaved?: () => void }) {
  const [plan,setPlan]=useState<Plan>(emptyPlan()); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState(''); const [saved,setSaved]=useState(false);
  useEffect(()=>{ async function load(){ setLoading(true); const supabase=getSupabaseBrowser(); const {data,error:queryError}=await supabase.from('treatment_plans').select('*').eq('patient_id',patientId).order('created_at',{ascending:false}).limit(1).maybeSingle(); if(queryError)setError(queryError.message); if(data)setPlan({...emptyPlan(),...data} as Plan); setLoading(false); } void load(); },[patientId]);
  function field(name:keyof Plan,value:string){setSaved(false);setPlan(current=>({...current,[name]:value}));}
  async function submit(event:FormEvent){event.preventDefault();setSaving(true);setError('');setSaved(false);const supabase=getSupabaseBrowser();const payload={...plan,patient_id:patientId,psychologist_id:psychologistId||null,target_end_on:plan.target_end_on||null,updated_at:new Date().toISOString()};const result=plan.id?await supabase.from('treatment_plans').update(payload).eq('id',plan.id).select('*').single():await supabase.from('treatment_plans').insert(payload).select('*').single();if(result.error)setError(result.error.message);else{setPlan(result.data as Plan);setSaved(true);onSaved?.();}setSaving(false);}
  if(loading)return <section className="card record-section"><div className="empty-state">Cargando plan terapéutico...</div></section>;
  return <form className="card record-section" onSubmit={submit}><div className="section-heading"><div><span className="eyebrow">Tratamiento</span><h2><ClipboardCheck size={21}/> Plan terapéutico</h2><p className="muted">Documenta formulación, objetivo general, enfoque, frecuencia y horizonte del tratamiento.</p></div><button className="btn btn-primary" disabled={saving} type="submit"><Save size={17}/>{saving?'Guardando...':'Guardar plan'}</button></div>{error?<div className="clinical-alert"><strong>No fue posible guardar</strong><span>{error}</span></div>:null}{saved?<div className="notice-card">Plan terapéutico guardado correctamente.</div>:null}<div className="form-grid"><label>Nombre del plan<input required value={plan.title} onChange={e=>field('title',e.target.value)}/></label><label>Estado<select value={plan.status} onChange={e=>field('status',e.target.value)}><option value="draft">Borrador</option><option value="active">Activo</option><option value="completed">Completado</option><option value="cancelled">Cancelado</option></select></label><label>Formulación clínica<textarea rows={4} value={plan.clinical_formulation} onChange={e=>field('clinical_formulation',e.target.value)}/></label><label>Objetivo general<textarea rows={4} value={plan.general_objective} onChange={e=>field('general_objective',e.target.value)}/></label><label>Enfoque / modelo terapéutico<input value={plan.approach} onChange={e=>field('approach',e.target.value)} placeholder="Ej. Cognitivo-conductual"/></label><label>Frecuencia<input value={plan.frequency} onChange={e=>field('frequency',e.target.value)} placeholder="Ej. Semanal"/></label><label>Inicio<input type="date" value={plan.starts_on} onChange={e=>field('starts_on',e.target.value)}/></label><label>Fecha objetivo<input type="date" value={plan.target_end_on} onChange={e=>field('target_end_on',e.target.value)}/></label></div></form>;
}