'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';
import { ArrowLeft, FileText, Printer, ReceiptText } from 'lucide-react';
import { getSupabaseBrowser } from '@/lib/supabase-browser';

type Patient={first_name?:string|null;last_name?:string|null};
type Billing={id:number;concept:string;currency:string;patients?:Patient|null};
type Payment={id:number;amount:number;payment_method?:string|null;reference?:string|null;paid_at:string;billing_items?:Billing|null;payment_receipts?:{id:number;receipt_number:string;issued_at:string}[]|null};
type ReceiptPayload={receipt:{id:number;receipt_number:string;issued_at:string;notes?:string|null};payment:Payment;item:Billing};
const money=(n:number,c='MXN')=>new Intl.NumberFormat('es-MX',{style:'currency',currency:c}).format(n||0);
const patientName=(p?:Patient|null)=>p?`${p.first_name||''} ${p.last_name||''}`.trim()||'Paciente':'Paciente';

export default function ReceiptsPage(){
 const [rows,setRows]=useState<Payment[]>([]);const [message,setMessage]=useState('');const [busy,setBusy]=useState<number|null>(null);const [receipt,setReceipt]=useState<ReceiptPayload|null>(null);
 async function load(){const s=getSupabaseBrowser();const {data,error}=await s.from('payments').select('id,amount,payment_method,reference,paid_at,billing_items(id,concept,currency,patients(first_name,last_name)),payment_receipts(id,receipt_number,issued_at)').order('paid_at',{ascending:false}).limit(200);if(error)setMessage(error.message);else setRows((data||[]) as unknown as Payment[]);}
 useEffect(()=>{void load();},[]);
 async function issue(paymentId:number){setBusy(paymentId);setMessage('');try{const s=getSupabaseBrowser();const {data:{session}}=await s.auth.getSession();if(!session)throw new Error('Sesión no válida.');const response=await fetch('/api/finance/receipts',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({paymentId})});const payload=await response.json();if(!response.ok)throw new Error(payload.error||'No se pudo generar el recibo.');setReceipt(payload as ReceiptPayload);await load();}catch(error){setMessage(error instanceof Error?error.message:'No se pudo generar el recibo.');}finally{setBusy(null);}}
 return <div className="page-shell"><div className="record-breadcrumb"><Link href="/finance"><ArrowLeft size={15}/> Finanzas</Link><span>/</span><strong>Recibos</strong></div><div className="page-head"><div><span className="eyebrow">Cobranza</span><h1>Recibos de pago</h1><p className="muted">Emite comprobantes internos a partir de pagos ya registrados.</p></div></div>{message?<div className="clinical-alert" style={{marginBottom:18}}><span>{message}</span></div>:null}<section className="card record-main-card"><div className="section-heading"><div><span className="eyebrow">Pagos</span><h2>Historial</h2></div></div>{rows.length?<div className="appointment-list">{rows.map(row=>{const item=Array.isArray(row.billing_items)?row.billing_items[0]:row.billing_items;const existing=row.payment_receipts?.[0];return <div className="appointment-item" key={row.id}><ReceiptText size={18}/><div><strong>{patientName(item?.patients)} · {item?.concept||'Pago'}</strong><small>{money(Number(row.amount),item?.currency||'MXN')} · {row.payment_method||'Método no indicado'} · {new Intl.DateTimeFormat('es-MX',{dateStyle:'medium',timeStyle:'short'}).format(new Date(row.paid_at))}</small></div>{existing?<span className="soft-chip">{existing.receipt_number}</span>:<button className="btn btn-primary btn-small" disabled={busy===row.id} onClick={()=>void issue(row.id)}><FileText size={15}/> {busy===row.id?'Generando...':'Emitir recibo'}</button>}</div>})}</div>:<div className="empty-state compact-empty">No hay pagos registrados.</div>}</section>{receipt?<section className="card record-section" style={{marginTop:22}}><div className="section-heading"><div><span className="eyebrow">Comprobante</span><h2>{receipt.receipt.receipt_number}</h2></div><button className="btn btn-secondary" onClick={()=>window.print()}><Printer size={16}/> Imprimir</button></div><div style={{display:'grid',gap:8}}><strong>{patientName(receipt.item.patients)}</strong><span>{receipt.item.concept}</span><span>Importe recibido: {money(Number(receipt.payment.amount),receipt.item.currency)}</span><span>Método: {receipt.payment.payment_method||'No indicado'}</span>{receipt.payment.reference?<span>Referencia: {receipt.payment.reference}</span>:null}<small className="muted">Emitido el {new Intl.DateTimeFormat('es-MX',{dateStyle:'long',timeStyle:'short'}).format(new Date(receipt.receipt.issued_at))}</small><small className="muted">Comprobante interno. No sustituye un CFDI.</small></div></section>:null}</div>;
}
