'use client';

import { FormEvent, useEffect, useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, Plus, Tag, Trash2 } from 'lucide-react';
import { getSupabaseBrowser } from '@/lib/supabase-browser';

type Rate={id:number;name:string;description?:string|null;amount:number;currency:string;consultation_mode?:string|null;duration_minutes?:number|null;active:boolean};
const money=(n:number,c='MXN')=>new Intl.NumberFormat('es-MX',{style:'currency',currency:c}).format(n||0);

export default function RatesPage(){
 const [rates,setRates]=useState<Rate[]>([]);const [message,setMessage]=useState('');const [saving,setSaving]=useState(false);const [form,setForm]=useState({name:'Consulta psicológica',description:'',amount:'',mode:'Presencial',duration:'60'});
 async function load(){const s=getSupabaseBrowser();const {data,error}=await s.from('service_rates').select('id,name,description,amount,currency,consultation_mode,duration_minutes,active').order('active',{ascending:false}).order('name');if(error)setMessage(error.message);else setRates((data||[]) as Rate[]);}
 useEffect(()=>{void load();},[]);
 async function submit(e:FormEvent){e.preventDefault();setSaving(true);setMessage('');try{const amount=Number(form.amount),duration=Number(form.duration);if(!form.name.trim()||!Number.isFinite(amount)||amount<0)throw new Error('Revisa nombre e importe.');const s=getSupabaseBrowser();const {data:{user}}=await s.auth.getUser();if(!user)throw new Error('Sesión no válida.');const {error}=await s.from('service_rates').insert({psychologist_id:user.id,name:form.name.trim(),description:form.description.trim()||null,amount,currency:'MXN',consultation_mode:form.mode||null,duration_minutes:Number.isFinite(duration)&&duration>0?duration:null,active:true});if(error)throw error;setForm({name:'Consulta psicológica',description:'',amount:'',mode:'Presencial',duration:'60'});await load();setMessage('Tarifa creada.');}catch(err){setMessage(err instanceof Error?err.message:'No se pudo crear la tarifa.');}finally{setSaving(false);}}
 async function toggle(rate:Rate){const s=getSupabaseBrowser();const {error}=await s.from('service_rates').update({active:!rate.active,updated_at:new Date().toISOString()}).eq('id',rate.id);if(error)setMessage(error.message);else await load();}
 async function remove(rate:Rate){if(!confirm(`¿Eliminar la tarifa ${rate.name}?`))return;const s=getSupabaseBrowser();const {error}=await s.from('service_rates').delete().eq('id',rate.id);if(error)setMessage('No se puede eliminar si ya está relacionada con movimientos. Puedes desactivarla.');else await load();}
 return <div className="page-shell"><div className="record-breadcrumb"><Link href="/finance"><ArrowLeft size={15}/> Finanzas</Link><span>/</span><strong>Tarifas</strong></div><div className="page-head"><div><span className="eyebrow">Catálogo financiero</span><h1>Tarifas y servicios</h1><p className="muted">Define precios por tipo y modalidad de consulta.</p></div></div>{message?<div className="clinical-alert" style={{marginBottom:18}}><span>{message}</span></div>:null}<div className="record-grid"><section className="card record-main-card"><div className="section-heading"><div><span className="eyebrow">Servicios</span><h2>Tarifas configuradas</h2></div></div>{rates.length?<div className="appointment-list">{rates.map(rate=><div className="appointment-item" key={rate.id}><Tag size={18}/><div><strong>{rate.name}</strong><small>{rate.consultation_mode||'Cualquier modalidad'} · {rate.duration_minutes?`${rate.duration_minutes} min · `:''}{money(Number(rate.amount),rate.currency)}</small></div><span className="soft-chip">{rate.active?'Activa':'Inactiva'}</span><button className="btn btn-secondary btn-small" onClick={()=>void toggle(rate)}>{rate.active?'Desactivar':'Activar'}</button><button className="btn btn-secondary btn-small" onClick={()=>void remove(rate)} title="Eliminar"><Trash2 size={15}/></button></div>)}</div>:<div className="empty-state compact-empty">No hay tarifas configuradas.</div>}</section><aside className="card record-side-card"><span className="eyebrow">Nuevo servicio</span><h2>Agregar tarifa</h2><form className="form" onSubmit={submit}><label className="field">Nombre<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label className="field">Descripción<textarea rows={3} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label className="field">Importe<input type="number" min="0" step="0.01" required value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></label><label className="field">Modalidad<select value={form.mode} onChange={e=>setForm({...form,mode:e.target.value})}><option>Presencial</option><option>En línea</option><option value="">Cualquier modalidad</option></select></label><label className="field">Duración (minutos)<input type="number" min="1" value={form.duration} onChange={e=>setForm({...form,duration:e.target.value})}/></label><button className="btn btn-primary" disabled={saving}><Plus size={16}/> {saving?'Guardando...':'Agregar tarifa'}</button></form></aside></div></div>;
}
