-- PsyCore Base v2
-- Sincroniza consultorios, agenda, disponibilidad y validación de conflictos.
-- Esta migración es idempotente: puede ejecutarse más de una vez.

begin;

-- 1. Consultorios
create table if not exists public.consulting_rooms (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  color text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists uq_consulting_rooms_name
  on public.consulting_rooms (lower(name));

-- 2. Columnas modernas de appointments
alter table public.appointments
  add column if not exists room_id bigint,
  add column if not exists consultation_mode text not null default 'Presencial',
  add column if not exists duration_minutes integer not null default 50,
  add column if not exists updated_at timestamptz not null default now();

-- Normaliza datos existentes antes de agregar restricciones.
update public.appointments
set duration_minutes = 50
where duration_minutes is null or duration_minutes < 15 or duration_minutes > 480;

update public.appointments
set consultation_mode = 'Presencial'
where consultation_mode is null or btrim(consultation_mode) = '';

-- 3. Llave foránea de consultorio
DO $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'appointments_room_id_fkey'
      and conrelid = 'public.appointments'::regclass
  ) then
    alter table public.appointments
      add constraint appointments_room_id_fkey
      foreign key (room_id)
      references public.consulting_rooms(id)
      on delete set null;
  end if;
end $$;

-- 4. Restricciones de appointments
DO $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'appointments_duration_minutes_check'
      and conrelid = 'public.appointments'::regclass
  ) then
    alter table public.appointments
      add constraint appointments_duration_minutes_check
      check (duration_minutes between 15 and 480);
  end if;
end $$;

-- 5. Índices de agenda
create index if not exists idx_appointments_psychologist_starts_at
  on public.appointments(psychologist_id, starts_at);

create index if not exists idx_appointments_patient_starts_at
  on public.appointments(patient_id, starts_at);

create index if not exists idx_appointments_room_starts_at
  on public.appointments(room_id, starts_at)
  where room_id is not null;

-- 6. Horarios laborales
create table if not exists public.calendar_working_hours (
  id bigint generated by default as identity primary key,
  psychologist_id uuid not null references public.profiles(id) on delete cascade,
  day_of_week smallint not null check (day_of_week between 0 and 6),
  start_time time not null,
  end_time time not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint calendar_working_hours_valid_range check (end_time > start_time)
);

create index if not exists idx_calendar_working_hours_psychologist_day
  on public.calendar_working_hours(psychologist_id, day_of_week);

-- 7. Bloqueos, vacaciones y comidas
create table if not exists public.calendar_time_blocks (
  id bigint generated by default as identity primary key,
  psychologist_id uuid not null references public.profiles(id) on delete cascade,
  title text not null,
  block_type text not null default 'Bloqueo',
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  notes text,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint calendar_time_blocks_valid_range check (ends_at > starts_at)
);

DO $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'calendar_time_blocks_type_check'
      and conrelid = 'public.calendar_time_blocks'::regclass
  ) then
    alter table public.calendar_time_blocks
      add constraint calendar_time_blocks_type_check
      check (block_type in ('Bloqueo','Vacaciones','Comida','Personal','Otro'));
  end if;
end $$;

create index if not exists idx_calendar_time_blocks_psychologist_range
  on public.calendar_time_blocks(psychologist_id, starts_at, ends_at);

-- 8. Seguridad RLS
alter table public.consulting_rooms enable row level security;
alter table public.calendar_working_hours enable row level security;
alter table public.calendar_time_blocks enable row level security;

drop policy if exists "Authenticated users can read consulting rooms" on public.consulting_rooms;
create policy "Authenticated users can read consulting rooms"
on public.consulting_rooms for select
to authenticated using (true);

drop policy if exists "Authenticated users can manage consulting rooms" on public.consulting_rooms;
create policy "Authenticated users can manage consulting rooms"
on public.consulting_rooms for all
to authenticated using (true) with check (true);

drop policy if exists "Authenticated users can read working hours" on public.calendar_working_hours;
create policy "Authenticated users can read working hours"
on public.calendar_working_hours for select
to authenticated using (true);

drop policy if exists "Authenticated users can manage working hours" on public.calendar_working_hours;
create policy "Authenticated users can manage working hours"
on public.calendar_working_hours for all
to authenticated using (true) with check (true);

drop policy if exists "Authenticated users can read calendar blocks" on public.calendar_time_blocks;
create policy "Authenticated users can read calendar blocks"
on public.calendar_time_blocks for select
to authenticated using (true);

drop policy if exists "Authenticated users can manage calendar blocks" on public.calendar_time_blocks;
create policy "Authenticated users can manage calendar blocks"
on public.calendar_time_blocks for all
to authenticated using (true) with check (true);

-- 9. Función central de conflictos
create or replace function public.check_appointment_conflicts(
  p_appointment_id bigint,
  p_patient_id bigint,
  p_psychologist_id uuid,
  p_room_id bigint,
  p_starts_at timestamptz,
  p_duration_minutes integer
)
returns jsonb
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_ends_at timestamptz;
  v_day smallint;
  v_local_start time;
  v_local_end time;
  v_has_schedule boolean;
  v_conflicts text[] := array[]::text[];
begin
  if p_starts_at is null or coalesce(p_duration_minutes, 0) <= 0 then
    return jsonb_build_object(
      'valid', false,
      'conflicts', jsonb_build_array('La fecha y la duración son obligatorias.')
    );
  end if;

  if p_psychologist_id is null then
    return jsonb_build_object(
      'valid', false,
      'conflicts', jsonb_build_array('La cita debe tener una psicóloga responsable.')
    );
  end if;

  v_ends_at := p_starts_at + make_interval(mins => p_duration_minutes);
  v_day := extract(dow from p_starts_at at time zone 'America/Mexico_City')::smallint;
  v_local_start := (p_starts_at at time zone 'America/Mexico_City')::time;
  v_local_end := (v_ends_at at time zone 'America/Mexico_City')::time;

  select exists(
    select 1
    from public.calendar_working_hours
    where psychologist_id = p_psychologist_id
      and active = true
  ) into v_has_schedule;

  if v_has_schedule and not exists(
    select 1
    from public.calendar_working_hours
    where psychologist_id = p_psychologist_id
      and day_of_week = v_day
      and active = true
      and start_time <= v_local_start
      and end_time >= v_local_end
  ) then
    v_conflicts := array_append(v_conflicts, 'La cita está fuera del horario laboral de la psicóloga.');
  end if;

  if exists(
    select 1
    from public.calendar_time_blocks
    where psychologist_id = p_psychologist_id
      and starts_at < v_ends_at
      and ends_at > p_starts_at
  ) then
    v_conflicts := array_append(v_conflicts, 'La psicóloga tiene vacaciones o un bloqueo en ese horario.');
  end if;

  if exists(
    select 1
    from public.appointments a
    where a.psychologist_id = p_psychologist_id
      and a.id <> coalesce(p_appointment_id, -1)
      and coalesce(a.status, '') not in ('Cancelada','Cancelado')
      and a.starts_at < v_ends_at
      and a.starts_at + make_interval(mins => coalesce(a.duration_minutes, 50)) > p_starts_at
  ) then
    v_conflicts := array_append(v_conflicts, 'La psicóloga ya tiene otra cita en ese horario.');
  end if;

  if p_patient_id is not null and exists(
    select 1
    from public.appointments a
    where a.patient_id = p_patient_id
      and a.id <> coalesce(p_appointment_id, -1)
      and coalesce(a.status, '') not in ('Cancelada','Cancelado')
      and a.starts_at < v_ends_at
      and a.starts_at + make_interval(mins => coalesce(a.duration_minutes, 50)) > p_starts_at
  ) then
    v_conflicts := array_append(v_conflicts, 'El paciente ya tiene otra cita en ese horario.');
  end if;

  if p_room_id is not null and exists(
    select 1
    from public.appointments a
    where a.room_id = p_room_id
      and a.id <> coalesce(p_appointment_id, -1)
      and coalesce(a.status, '') not in ('Cancelada','Cancelado')
      and a.starts_at < v_ends_at
      and a.starts_at + make_interval(mins => coalesce(a.duration_minutes, 50)) > p_starts_at
  ) then
    v_conflicts := array_append(v_conflicts, 'El consultorio ya está ocupado en ese horario.');
  end if;

  return jsonb_build_object(
    'valid', coalesce(array_length(v_conflicts, 1), 0) = 0,
    'conflicts', to_jsonb(v_conflicts),
    'ends_at', v_ends_at
  );
end;
$$;

grant execute on function public.check_appointment_conflicts(bigint,bigint,uuid,bigint,timestamptz,integer)
to authenticated;

commit;

notify pgrst, 'reload schema';
