create table if not exists public.service_rates (
  id bigint generated by default as identity primary key,
  psychologist_id uuid references public.profiles(id) on delete cascade,
  name text not null,
  description text,
  amount numeric(12,2) not null check (amount >= 0),
  currency text not null default 'MXN',
  consultation_mode text,
  duration_minutes integer check (duration_minutes is null or duration_minutes > 0),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.payment_receipts (
  id bigint generated by default as identity primary key,
  payment_id bigint not null references public.payments(id) on delete cascade,
  receipt_number text not null unique,
  issued_at timestamptz not null default now(),
  issued_by uuid references public.profiles(id) on delete set null,
  notes text,
  created_at timestamptz not null default now()
);

alter table public.billing_items add column if not exists service_rate_id bigint references public.service_rates(id) on delete set null;
alter table public.billing_items add column if not exists source text not null default 'manual';
alter table public.billing_items add column if not exists updated_at timestamptz not null default now();

create unique index if not exists billing_items_appointment_auto_unique
  on public.billing_items(appointment_id)
  where appointment_id is not null and source = 'appointment_auto' and status <> 'cancelled';

create index if not exists service_rates_psychologist_idx on public.service_rates(psychologist_id, active);
create index if not exists payment_receipts_payment_idx on public.payment_receipts(payment_id);

alter table public.service_rates enable row level security;
alter table public.payment_receipts enable row level security;

do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='service_rates' and policyname='Authenticated access') then
    create policy "Authenticated access" on public.service_rates for all to authenticated using (true) with check (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='payment_receipts' and policyname='Authenticated access') then
    create policy "Authenticated access" on public.payment_receipts for all to authenticated using (true) with check (true);
  end if;
end $$;
