-- PsyCore Platform Foundation
-- Base para expediente avanzado, tratamiento, consentimientos, tareas, cobros,
-- recordatorios, portal del paciente y auditoría.

begin;

create table if not exists public.clinical_histories (
  id bigint generated by default as identity primary key,
  patient_id bigint not null references public.patients(id) on delete cascade,
  psychologist_id uuid references public.profiles(id) on delete set null,
  reason_for_consultation text,
  current_problem text,
  personal_history text,
  family_history text,
  medical_history text,
  psychosocial_history text,
  initial_impression text,
  diagnosis text,
  protective_factors text,
  risk_factors text,
  status text not null default 'active' check (status in ('active','closed','archived')),
  opened_at timestamptz not null default now(),
  closed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists idx_clinical_histories_patient on public.clinical_histories(patient_id, opened_at desc);

create table if not exists public.treatment_plans (
  id bigint generated by default as identity primary key,
  patient_id bigint not null references public.patients(id) on delete cascade,
  psychologist_id uuid references public.profiles(id) on delete set null,
  title text not null default 'Plan terapéutico',
  clinical_formulation text,
  general_objective text,
  approach text,
  frequency text,
  status text not null default 'active' check (status in ('draft','active','completed','cancelled')),
  starts_on date,
  target_end_on date,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists idx_treatment_plans_patient on public.treatment_plans(patient_id, created_at desc);

create table if not exists public.treatment_objectives (
  id bigint generated by default as identity primary key,
  treatment_plan_id bigint not null references public.treatment_plans(id) on delete cascade,
  title text not null,
  description text,
  target_value numeric,
  current_value numeric,
  progress_percent integer not null default 0 check (progress_percent between 0 and 100),
  status text not null default 'active' check (status in ('active','achieved','paused','cancelled')),
  due_on date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists idx_treatment_objectives_plan on public.treatment_objectives(treatment_plan_id, status);

create table if not exists public.patient_consents (
  id bigint generated by default as identity primary key,
  patient_id bigint not null references public.patients(id) on delete cascade,
  consent_type text not null,
  document_version text not null default '1.0',
  document_text text not null,
  signer_name text,
  signer_relationship text,
  signed_at timestamptz,
  signature_data text,
  ip_address inet,
  revoked_at timestamptz,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);
create index if not exists idx_patient_consents_patient on public.patient_consents(patient_id, created_at desc);

create table if not exists public.therapy_homework (
  id bigint generated by default as identity primary key,
  patient_id bigint not null references public.patients(id) on delete cascade,
  psychologist_id uuid references public.profiles(id) on delete set null,
  title text not null,
  instructions text,
  due_at timestamptz,
  status text not null default 'pending' check (status in ('pending','in_progress','completed','cancelled')),
  patient_response text,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists idx_therapy_homework_patient on public.therapy_homework(patient_id, status, due_at);

create table if not exists public.patient_portal_invites (
  id bigint generated by default as identity primary key,
  patient_id bigint not null references public.patients(id) on delete cascade,
  email text not null,
  token_hash text not null unique,
  expires_at timestamptz not null,
  accepted_at timestamptz,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.appointment_reminders (
  id bigint generated by default as identity primary key,
  appointment_id bigint not null references public.appointments(id) on delete cascade,
  channel text not null check (channel in ('email','whatsapp','sms','portal')),
  scheduled_at timestamptz not null,
  sent_at timestamptz,
  status text not null default 'pending' check (status in ('pending','sent','failed','cancelled')),
  provider_message_id text,
  error_message text,
  created_at timestamptz not null default now()
);
create index if not exists idx_appointment_reminders_pending on public.appointment_reminders(status, scheduled_at);

create table if not exists public.billing_items (
  id bigint generated by default as identity primary key,
  patient_id bigint not null references public.patients(id) on delete restrict,
  appointment_id bigint references public.appointments(id) on delete set null,
  psychologist_id uuid references public.profiles(id) on delete set null,
  concept text not null,
  amount numeric(12,2) not null check (amount >= 0),
  discount numeric(12,2) not null default 0 check (discount >= 0),
  currency text not null default 'MXN',
  status text not null default 'pending' check (status in ('pending','partial','paid','cancelled','refunded')),
  due_on date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists idx_billing_items_patient on public.billing_items(patient_id, status, created_at desc);

create table if not exists public.payments (
  id bigint generated by default as identity primary key,
  billing_item_id bigint not null references public.billing_items(id) on delete restrict,
  amount numeric(12,2) not null check (amount > 0),
  payment_method text,
  reference text,
  paid_at timestamptz not null default now(),
  received_by uuid references public.profiles(id) on delete set null,
  notes text,
  created_at timestamptz not null default now()
);
create index if not exists idx_payments_billing_item on public.payments(billing_item_id, paid_at desc);

create table if not exists public.audit_events (
  id bigint generated by default as identity primary key,
  actor_id uuid references public.profiles(id) on delete set null,
  action text not null,
  entity_type text not null,
  entity_id text,
  patient_id bigint references public.patients(id) on delete set null,
  metadata jsonb not null default '{}'::jsonb,
  ip_address inet,
  user_agent text,
  created_at timestamptz not null default now()
);
create index if not exists idx_audit_events_patient on public.audit_events(patient_id, created_at desc);
create index if not exists idx_audit_events_entity on public.audit_events(entity_type, entity_id, created_at desc);

alter table public.clinical_histories enable row level security;
alter table public.treatment_plans enable row level security;
alter table public.treatment_objectives enable row level security;
alter table public.patient_consents enable row level security;
alter table public.therapy_homework enable row level security;
alter table public.patient_portal_invites enable row level security;
alter table public.appointment_reminders enable row level security;
alter table public.billing_items enable row level security;
alter table public.payments enable row level security;
alter table public.audit_events enable row level security;

-- Las políticas de alcance por psicólogo se endurecerán junto con la consolidación
-- de organizaciones. Por ahora se exige autenticación, manteniendo compatibilidad
-- con el modelo de permisos actual de PsyCore.
do $$
declare
  t text;
begin
  foreach t in array array[
    'clinical_histories','treatment_plans','treatment_objectives','patient_consents',
    'therapy_homework','patient_portal_invites','appointment_reminders','billing_items',
    'payments','audit_events'
  ] loop
    execute format('drop policy if exists "Authenticated access" on public.%I', t);
    execute format('create policy "Authenticated access" on public.%I for all to authenticated using (true) with check (true)', t);
  end loop;
end $$;

commit;
notify pgrst, 'reload schema';
